AWSTemplateFormatVersion: "2010-09-09"
Description: "Kittens Carousel Application Stack"

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'

Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref 't2.micro'
      KeyName: 'first_key'
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash
            # Download and deploy application files
            git clone https://github.com/tahabozoyuk/Kittens-Carousel-Static-Website-AWS-EC2-Cloudformation.git /var/www/html/
            # Install Apache Web Server
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            # Set ownership and permissions
            chown -R apache:apache /var/www/html/
            chmod -R 755 /var/www/html/
          - {}

  WebServerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group for the Web Server"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
      Tags:
        - Key: "Name"
          Value: "Web Server of ${AWS::StackName}"
