AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This is my first
  template for
  using Cloudformation.
    
Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'

Resources:
  Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: 't2.micro'
      ImageId: !Ref LatestAmiId
      KeyName: first_key # Use your own keypair without .pem
      SecurityGroups: 
        - !Ref TahaSecGrp
      Tags: 
        - Key: Name
          Value: Taha-instance

  TahaSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows only SSH connection # Required
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0