AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This is my first
  template for
  using Cloudformation.
    
Resources:
  TahaInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0230bd60aa48260c6
      InstanceType: t2.micro
      KeyName: first_key # Use your own keypair without .pem
      SecurityGroups: 
        - !Ref TahaSecGrp
      Tags: 
        - Key: Name
          Value: Taha-instance

  TahaSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows only SSH connection # Required
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0